apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jupyter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jupyter.selectorLabels" . | nindent 8 }}
    spec:
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jupyter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jupyter
              containerPort: 8888
              protocol: TCP
            - name: tensorboard
              containerPort: 6006
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/status
              port: jupyter
          readinessProbe:
            httpGet:
              path: /api/status
              port: jupyter
          {{- if .Values.command.enabled }}
          command: {{ .Values.command.value }}
          args: {{ .Values.command.args }}
          {{- end }}
          {{- if .Values.rootUser }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- with .Values.envVariables }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
