apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: jupyter
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
    - port: 6006
      targetPort: tensorboard
      protocol: TCP
      name: tensorboard
  selector:
    {{- include "jupyter.selectorLabels" . | nindent 4 }}
