jupyter:
  image:
    repository: nickbrown1/jupyter-pytorch-gpu
    pullPolicy: IfNotPresent
    tag: "8135053194"

  resources:
    limits:
      memory: 148Gi
      nvidia.com/gpu: 2
    requests:
      memory: 8Gi
      cpu: '12'

  envVariables:
    - name: JUPYTER_ENABLE_LAB
      value: "yes"
    - name: PASSWORD
    - name: GRANT_SUDO
      value: "yes"
    - name: JUPYTER_PORT
      value: "8888"

  volumes:
    - name: model-volume
      hostPath:
        readOnly: true
        path: /mnt/nvme0/models/

  volumeMounts:
    - mountPath: /app/models
      name: model-volume

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: jupyter-ex.k3s.nickbrown.ai
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]

  nodeSelector:
    nvidia.com/gpu.product: "NVIDIA-GeForce-RTX-4090"